-- Run only if your properties table is missing columns used by the API.
USE real_estate_db;

ALTER TABLE properties
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS price DECIMAL(12, 2),
  ADD COLUMN IF NOT EXISTS location VARCHAR(255),
  ADD COLUMN IF NOT EXISTS bedrooms INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS bathrooms INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS square_feet INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS image_url VARCHAR(500),
  ADD COLUMN IF NOT EXISTS type VARCHAR(50),
  ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'available',
  ADD COLUMN IF NOT EXISTS features JSON,
  ADD COLUMN IF NOT EXISTS agent VARCHAR(255),
  ADD COLUMN IF NOT EXISTS created_date DATETIME DEFAULT CURRENT_TIMESTAMP;
